name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly

    steps:
    - name: Install dependencies
      run: sudo apt-get install -y libclang-dev
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - name: Build
      run: cargo build --verbose
    # clippy
    - run: rustup component add clippy
      if: matrix.rust == 'beta' || matrix.rust == 'stable'
    - working-directory: ${{ matrix.conf.name }}
      name: clippy ${{ matrix.conf.name }}
      run: cargo clippy --all-targets -- -D warnings
      if: matrix.rust == 'beta' || matrix.rust == 'stable'
    # fmt
    - working-directory: ${{ matrix.conf.name }}
      name: rustfmt ${{ matrix.conf.name }}
      run: cargo fmt --check
      if: matrix.rust == 'beta' || matrix.rust == 'stable'
    # tests
    - name: Run tests
      run: cargo test --verbose
